name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! Thanks for creating YOUR first Issue in this repo. We hope to see you contributing more often... If you would like to be a dev of this project, please join our discord [here](https://discord.com/invite/FtNJE4QqG4]"
        pr-message: "Hey! Thanks for creating YOUR first Pull Request in this repo. We hope to see you contributing more often... If you would like to be a dev of this project, please join our discord [here](https://discord.com/invite/FtNJE4QqG4]"
